server:
  port: 8081
  error:
    include-stacktrace: never

spring:
  application:
    name: person-crud
  datasource:
    url: jdbc:h2:mem:dsmeta
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

twilio:
  sid: ${TWILIO_SID}
  key: ${TWILIO_KEY}
  phone:
    from: ${TWILIO_PHONE_FROM}
    to: ${TWILIO_PHONE_TO}