server:
  error:
    include-stacktrace: never

spring:
  application:
    name: person-crud
  datasource:
    url: jdbc:mysql://localhost:3306/dsmeta?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG